apiVersion: apps/v1
kind: Deployment
metadata:
    name: java-app-deployment
    namespace: kubernetes-cluster-tushaartiwari
    labels:
        app: java-app
spec:
    replicas: 4
    selector:
        matchLabels:
            app: java-app
    template:
        metadata:
            labels:
                app: java-app
        spec:
            containers:
                - name: java-app
                  image: tushaar28/nagp_devops:latest
                  ports:
                    - name: http
                      containerPort: 7200
                      protocol: TCP
                  resources:
                    requests:
                        memory: "250Mi"
                        cpu: "250m"
                    limits:
                        memory: "500Mi"
                        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: java-app
    namespace: kubernetes-cluster-tushaartiwari
spec:
    type: NodePort
    selector:
        app: java-app
    ports:
        - protocol: TCP
          nodePort: 30157
          port: 7200
          targetPort: 7200
    